In [ ]:
# step1 - we have to import the data set to the colab
import pandas as pd #pd is a nickname of pandas we have to use pd instead of pandas in full code
df=pd.read_csv('CSV.csv')#df is a variable ,read_csv is a predefined function from pandas package


In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#step2 - grouping the input and output coloumns
#we use iloc
X=df.iloc[:,0:-1]

In [ ]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
y=df.iloc[:,-1]#slicing the output coloumn

In [ ]:
type(y)

pandas.core.series.Series

In [ ]:
X=X.values

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
y=y.values

In [ ]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
#step3:handling the missing data
#scenerio 1 missing value in numerical coloumn:we have to do mean of remaining or average of the remaining values
#scenerio 2 missing values in non numerical coloumns like names etc:we have to replace the empty place by highly repeated name or value
#senerio  3 missing values in huge data set example 2/20000 rows:we have to remove those empty 2 rows from the data set
import numpy as np
from sklearn.impute import SimpleImputer
#simple imputer is a class from scikitlearn used to find mean mode etc or to assign new values which is empty
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])



In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
# step4 : handling catogorial data means converting text data to numerical data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
#label encoder is a class which was imported from sl.preprocessing library it is used to convert catogorial data to binary data
#coloumntransformer is a class imported from skcompose used to apply changes to coloumns or change numeric data to binary data
#alexa-0,0,1
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')#encoder is a method which converts text to numeric
X=ct.fit_transform(X)

In [ ]:
X


array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [ ]:
#label encoder is a class which is used to output only
#onehotencoder is applied for input only
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [ ]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#step5:split the data into testing and training
from sklearn.model_selection import train_test_split#it is a class imported from sklearn.modelselection used to split data into testing and training
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
X,y

(array([[1.0, 0.0, 0.0, 44.0, 72000.0],
        [0.0, 0.0, 1.0, 27.0, 48000.0],
        [0.0, 1.0, 0.0, 30.0, 54000.0],
        [0.0, 0.0, 1.0, 38.0, 61000.0],
        [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
        [1.0, 0.0, 0.0, 35.0, 58000.0],
        [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
        [1.0, 0.0, 0.0, 48.0, 79000.0],
        [0.0, 1.0, 0.0, 50.0, 83000.0],
        [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object),
 array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1]))

In [ ]:
X_test

array([[1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object)

In [ ]:
X_train

array([[0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [ ]:
y_test

array([1, 1])

In [ ]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 1])

In [ ]:
#step6:feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [ ]:
X_train

array([[0.0, 0.0, 1.0, 0.07725428517035086, -0.08059831939452457],
       [0.0, 1.0, 0.0, -1.0937580374118077, -0.7253848745507211],
       [0.0, 0.0, 1.0, -1.5328876583801172, -1.278059064684604],
       [0.0, 0.0, 1.0, 0.19110270542139418, -0.9096096045953487],
       [1.0, 0.0, 0.0, -0.06912225515241897, 0.4720758707393582],
       [1.0, 0.0, 0.0, 0.9555135271069698, 0.9326376958509272],
       [0.0, 1.0, 0.0, 1.8337727690435888, 1.9458737110963789],
       [1.0, 0.0, 0.0, -0.3618753357979586, -0.3569354144614659]],
      dtype=object)

In [ ]:
X_test

array([[1.0, 0.0, 0.0, 1.5410196883980491, 1.5774242510071237],
       [0.0, 1.0, 0.0, 0.3700073658158905, 0.17526936122301404]],
      dtype=object)

In [ ]:
#machine learning
#types in machinelearning
#1:supervisioned learning
#is used when our data is model tasks are classification or prediction
#2:unsupervisioned learning
#is used when our data is unlabeled data,model remembers the pattrens,we can perform predictions also.
#3:reinforcementlearning
#it performs tail and error method (model will learn from failures)
#based on task performing and dataset these are chategerised
#logistic regression algorithm=used when model performs classification tasks(tru or false etc only 2 presents)
#linear regression algorithm= have to apply when model performs prediction tasks (tells what is the value values comes in output in bunch of pattren)



In [33]:
#step7:applying algorithm to the data
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [36]:
Y_pred=classifier.predict(X_test)

In [37]:
Y_pred

array([0, 0])